[pytest]
norecursedirs =
    .git
    .venv
    .cache
    airflow/logs
    airflow/config
    airflow/plugins
    marketplace_analytics_dbt/target
    marketplace_analytics_dbt/target_*
    marketplace_analytics_dbt/logs
